Class Demo.Operations.Embedding.EmbeddingRequest Extends (%Persistent, Ens.Request)
{

Property Pdf As %Integer;

Storage Default
{
<Data name="EmbeddingRequestDefaultData">
<Subscript>"EmbeddingRequest"</Subscript>
<Value name="1">
<Value>Pdf</Value>
</Value>
<Value name="2">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^Demo.Opera34B7.EmbeddingReF572D</DataLocation>
<DefaultData>EmbeddingRequestDefaultData</DefaultData>
<IdLocation>^Demo.Opera34B7.EmbeddingReF572D</IdLocation>
<IndexLocation>^Demo.Opera34B7.EmbeddingReF572I</IndexLocation>
<StreamLocation>^Demo.Opera34B7.EmbeddingReF572S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
