Class Demo.Operations.Embedding.EmbeddingResponse Extends (%Persistent, Ens.Response)
{

Property NumberEmbeddings As %Integer;

Storage Default
{
<Data name="EmbeddingResponseDefaultData">
<Subscript>"EmbeddingResponse"</Subscript>
<Value name="1">
<Value>NumberEmbeddings</Value>
</Value>
<Value name="2">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^Demo.Opera34B7.EmbeddingRes2E9D</DataLocation>
<DefaultData>EmbeddingResponseDefaultData</DefaultData>
<IdLocation>^Demo.Opera34B7.EmbeddingRes2E9D</IdLocation>
<IndexLocation>^Demo.Opera34B7.EmbeddingRes2E9I</IndexLocation>
<StreamLocation>^Demo.Opera34B7.EmbeddingRes2E9S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
